name: Update badges

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths: ["readme.md", ".github/workflows/action.yml"]
  # schedule:
    ## Runs at 2am UTC
    # - cron: "*/1 * * * *"
jobs:
  update-readme:
    name: Update Readme with badges
    runs-on: [self-hosted, linux]
    permissions:
      contents: write
    steps:
      - name: Badges - ashish.chaurasia_ccv18@gla.ac.in
        uses: pemtajo/badge-readme@main
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          REPOSITORY: CloudNinjaDev/CloudNinjaDev # optional, By default, it will automatically use the repository who's executing the workflow.
          COMMIT_MESSAGE: "My commit message to update badges" # optional
          CREDLY_USER: ${{ secrets.CREDLY_PROFILE_1 }} # optional, but default will use the same from github
          CREDLY_SORT: RECENT # optional, this is the two forms from credly sort, more popular or recent first, by default use RECENT
      - name: Badges - ashish.chaurasia@octanner.com
        uses: pemtajo/badge-readme@main
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          REPOSITORY: CloudNinjaDev/CloudNinjaDev # optional, By default, it will automatically use the repository who's executing the workflow.
          COMMIT_MESSAGE: "My commit message to update badges" # optional
          CREDLY_USER: ${{ secrets.CREDLY_PROFILE_3 }} # optional, but default will use the same from github
          CREDLY_SORT: RECENT # optional, this is the two forms from credly sort, more popular or recent first, by default use RECENT
      - name: Badges - ashish1382000@gmail.com
        uses: pemtajo/badge-readme@main
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          REPOSITORY: CloudNinjaDev/CloudNinjaDev # optional, By default, it will automatically use the repository who's executing the workflow.
          COMMIT_MESSAGE: "My commit message to update badges" # optional
          CREDLY_USER: ${{ secrets.CREDLY_PROFILE_2 }} # optional, but default will use the same from github
          CREDLY_SORT: RECENT # optional, this is the two forms from credly sort, more popular or recent first, by default use RECENT
